export interface ISubscripcion {
  documento: number,
  apellido: string,
  nombre: string,
  telefono: number,
  celular: number,
  fax: number,
  email: string,
  direccion: string,
  zip: number,
  localidad: string,
  pais: string,
  arancel_adicional: number,
  arancel_categoria: string,
  arancel_pago: string,
  ponencia_presenta: boolean,
  ponencia_titulo: string,
  ponencia_area: string,
  ponencia_coautores: string,
  ponencia_institucion: string,
  acompanantes: number,
  confirmado: boolean,
}

export const EmptySubscripcion = {
  documento: 0,
  apellido: '',
  nombre: '',
  telefono: 0,
  celular: 0,
  fax: 0,
  email: '',
  direccion: '',
  zip: 0,
  localidad: '',
  pais: '',
  arancel_adicional: 0,
  arancel_categoria: '',
  arancel_pago: '',
  ponencia_presenta: false,
  ponencia_titulo: '',
  ponencia_area: '',
  ponencia_coautores: '',
  ponencia_institucion: '',
  acompanantes: 0,
  confirmado: false,
}
